### ISSUE TITLE
env -i TERM=$TERM ./21sh duplicate line in env

### ISSUE THREAD

**Issue by ndombre** [cactusfluo/ft_42sh#50]
run env -i TERM=$TERM ./21sh
when run env

the shell output :
TERM=xterm-256color
TERM=xterm-256color // this line is not normal !!

**Comment by ndombre** [comment]
env alweway duplic line

**Comment by cprouveu** [comment]
dans src > builtins > functions > fun_env_3.c
ligne 26 : (if !cur)
mettre -> if (cur)
