### ISSUE TITLE
OU logique

### ISSUE THREAD

**Issue by Gwojda** [cactusfluo/ft_42sh#81]
```
ls; aaaaaa || ls
```

-> exec qu'un seul ls au lieu de deux

**Comment by cprouveu** [comment]
retour des commandes a adapter ->
ls || aaaaaa
il faut que ls
aaaaaa || ls
il faut les deux

**Comment by cprouveu** [comment]
corrige si dans launcher_bin on ajoute un exit(ret) apres le unknow_command(cmd[0]).
