### ISSUE TITLE
HASH

### ISSUE THREAD

**Issue by Gwojda** [cactusfluo/ft_42sh#85]
UNE TABLE DE HASH CA DOIT MARCHER AUSSI AVEC LES BINAIRES CHRISTELLE

**Comment by cprouveu** [comment]
Gwojda est lord nullus

**Comment by Gwojda** [comment]
Une table de hash qui marche que pour les builtins, en statiques en plus, quel est l'interet ?

**Comment by Gwojda** [comment]
C'est pas a fermer ! Ca marche pas !!!!
